version: "3"
services:
  redis:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: redis
    hostname: redis
    image: icmdb/redis
    environment:
     - REDIS_DEBUG=
     - REDIS_DELAY=1
     - REDIS_PORT=6379
     - REDIS_REQUIREPASS=123654
     - REDIS_RENAME_COMMAND_CONFIG=renamedconfig
    #volumes:
    # - /proc/sys/net/core/somaxconn:/proc/sys/net/core/somaxconn:rw
    # - /sys/kernel/mm/transparent_hugepage/enabled:/sys/kernel/mm/transparent_hugepage/enabled:rw
    ports:
     - 6379:6379
    restart: always
